# vim: set sw=2 et :

language: cpp

script:
  - $CXX_COMPILER --version
  - env CXX=$CXX_COMPILER CXXFLAGS=$CXX_FLAGS LDFLAGS=$CXX_LDFLAGS make

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: gcc-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libboost-all-dev
      env:
        - CXX_COMPILER=g++-7
        - CXX_FLAGS=-fpermissive
          # old boost multiprecision doesn't work with new gcc

    - os: linux
      dist: xenial
      compiler: gcc-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - libboost-all-dev
      env:
        - CXX_COMPILER=g++-8
        - CXX_FLAGS=-fpermissive
          # old boost multiprecision doesn't work with new gcc

    - os: linux
      dist: focal
      compiler: gcc-9
      addons:
        apt:
          packages:
            - libboost-all-dev
      env:
        - CXX_COMPILER=g++

    - os: linux
      dist: focal
      compiler: clang-10
      addons:
        apt:
          packages:
            - libboost-all-dev
            - clang-10
      env:
        - CXX_COMPILER=clang++-10

    - os: osx
      osx_image: xcode10.2
      compiler: clang
      env:
        - CXX_COMPILER=clang++
